In [4]:
#PRINT REFERER

cari = 'halal'
def get_referer():
    referers=[]
    for i in range(2,6):
        referer = "https://www.tokopedia.com/search?navsource=&page={}&q={}&search_id=2025021200494626F385AC98EABB30EMBV&srp_component_id=02.01.00.00".format(i,cari)
        referers.append(referer)
    return referers

if __name__ == '__main__' :
    referers = get_referer()
    for i in range(0,len(referers)):
        referer = referers[i]
        print(referer)
        #data = scrape_data(param)

https://www.tokopedia.com/search?navsource=&page=2&q=halal&search_id=2025021200494626F385AC98EABB30EMBV&srp_component_id=02.01.00.00
https://www.tokopedia.com/search?navsource=&page=3&q=halal&search_id=2025021200494626F385AC98EABB30EMBV&srp_component_id=02.01.00.00
https://www.tokopedia.com/search?navsource=&page=4&q=halal&search_id=2025021200494626F385AC98EABB30EMBV&srp_component_id=02.01.00.00
https://www.tokopedia.com/search?navsource=&page=5&q=halal&search_id=2025021200494626F385AC98EABB30EMBV&srp_component_id=02.01.00.00

In [98]:
import requests
import json
import pandas as pd

#PAGE 1
url_target = 'https://gql.tokopedia.com/graphql/SearchProductV5Query'
cari = 'pakaian'
header0 = {'authority': 'gql.tokopedia.com',
  'sec-ch-ua-platform': "Windows",
  'sec-ch-ua': '"Not A(Brand";v="8", "Chromium";v="132", "Google Chrome";v="132"',
  'x-price-center': 'true',
  'iris_session_id': 'd3d3LnRva29wZWRpYS5jb20=.871ebaae251654628a14f3b7a16e6745.1739172229979',
  'bd-device-id': '7459658899563431431',
  'sec-ch-ua-mobile': '?0',
  'accept': '*/*',
  'content-type': 'application/json',
  'x-version': 'd05803b',
  'Referer': 'https://www.tokopedia.com/search?st=&q={cari}&srp_component_id=02.01.00.00&srp_page_id=&srp_page_title=&navsource=',
  'x-source': 'tokopedia-lite',
  'x-dark-mode': 'false',
  'tkpd-userid': '0',
  'x-device': 'desktop-0.0',
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36',
  'x-tkpd-lite-service': 'zeus'}
query0 = f'[{{"operationName":"SearchProductV5Query","variables":{{"params":"device=desktop&l_name=sre&navsource=&ob=23&page=1&q={cari}&related=true&rows=60&safe_search=false&scheme=https&shipping=&show_adult=false&source=search&srp_component_id=02.01.00.00&srp_page_id=&srp_page_title=&st=product&start=0&topads_bucket=true&unique_id=c5ed8ccdfa4b87c5d1c9097e7363f4c3&user_id=0&variants="}},"query":"query SearchProductV5Query($params: String\u0021) {{\\n  searchProductV5(params: $params) {{\\n    header {{\\n      totalData\\n      responseCode\\n      keywordProcess\\n      keywordIntention\\n      componentID\\n      isQuerySafe\\n      additionalParams\\n      backendFilters\\n      __typename\\n    }}\\n    data {{\\n      totalDataText\\n      banner {{\\n        position\\n        text\\n        applink\\n        url\\n        imageURL\\n        componentID\\n        trackingOption\\n        __typename\\n      }}\\n      redirection {{\\n        url\\n        __typename\\n      }}\\n      related {{\\n        relatedKeyword\\n        position\\n        trackingOption\\n        otherRelated {{\\n          keyword\\n          url\\n          applink\\n          componentID\\n          products {{\\n            oldID: id\\n            id: id_str_auto_\\n            name\\n            url\\n            applink\\n            mediaURL {{\\n              image\\n              __typename\\n            }}\\n            shop {{\\n              oldID: id\\n              id: id_str_auto_\\n              name\\n              city\\n              tier\\n              __typename\\n            }}\\n            badge {{\\n              oldID: id\\n              id: id_str_auto_\\n              title\\n              url\\n              __typename\\n            }}\\n            price {{\\n              text\\n              number\\n              __typename\\n            }}\\n            freeShipping {{\\n              url\\n              __typename\\n            }}\\n            labelGroups {{\\n              position\\n              title\\n              type\\n              url\\n              styles {{\\n                key\\n                value\\n                __typename\\n              }}\\n              __typename\\n            }}\\n            rating\\n            wishlist\\n            ads {{\\n              id\\n              productClickURL\\n              productViewURL\\n              productWishlistURL\\n              tag\\n              __typename\\n            }}\\n            meta {{\\n              oldWarehouseID: warehouseID\\n              warehouseID: warehouseID_str_auto_\\n              componentID\\n              __typename\\n            }}\\n            __typename\\n          }}\\n          __typename\\n        }}\\n        __typename\\n      }}\\n      suggestion {{\\n        currentKeyword\\n        suggestion\\n        query\\n        text\\n        componentID\\n        trackingOption\\n        __typename\\n      }}\\n      ticker {{\\n        oldID: id\\n        id: id_str_auto_\\n        text\\n        query\\n        applink\\n        componentID\\n        trackingOption\\n        __typename\\n      }}\\n      violation {{\\n        headerText\\n        descriptionText\\n        imageURL\\n        ctaURL\\n        ctaApplink\\n        buttonText\\n        buttonType\\n        __typename\\n      }}\\n      products {{\\n        oldID: id\\n        id: id_str_auto_\\n        name\\n        url\\n        applink\\n        mediaURL {{\\n          image\\n          image300\\n          videoCustom\\n          __typename\\n        }}\\n        shop {{\\n          oldID: id\\n          id: id_str_auto_\\n          name\\n          url\\n          city\\n          tier\\n          __typename\\n        }}\\n        badge {{\\n          oldID: id\\n          id: id_str_auto_\\n          title\\n          url\\n          __typename\\n        }}\\n        price {{\\n          text\\n          number\\n          range\\n          original\\n          discountPercentage\\n          __typename\\n        }}\\n        freeShipping {{\\n          url\\n          __typename\\n        }}\\n        labelGroups {{\\n          position\\n          title\\n          type\\n          url\\n          styles {{\\n            key\\n            value\\n            __typename\\n          }}\\n          __typename\\n        }}\\n        labelGroupsVariant {{\\n          title\\n          type\\n          typeVariant\\n          hexColor\\n          __typename\\n        }}\\n        category {{\\n          oldID: id\\n          id: id_str_auto_\\n          name\\n          breadcrumb\\n          gaKey\\n          __typename\\n        }}\\n        rating\\n        wishlist\\n        ads {{\\n          id\\n          productClickURL\\n          productViewURL\\n          productWishlistURL\\n          tag\\n          __typename\\n        }}\\n        meta {{\\n          oldParentID: parentID\\n          parentID: parentID_str_auto_\\n          oldWarehouseID: warehouseID\\n          warehouseID: warehouseID_str_auto_\\n          isImageBlurred\\n          isPortrait\\n          __typename\\n        }}\\n        __typename\\n      }}\\n      __typename\\n    }}\\n    __typename\\n  }}\\n}}\\n"}}]'

response0 = requests.post(url_target, headers=header0, data=query0)
products0=response0.json()[0]['data']['searchProductV5']['data']['products']

daftar_product0 = []
for i in range(len(products0)):
   nama_product = products0[i]['name']
   harga_product = products0[i]['price']['number']
   diskon_product  = products0[i]['price']['discountPercentage']
   harga_asli = products0[i]['price']['original']
   rating_product = products0[i]['rating']
   kategori = products0[i]['category']['name']
   lokasi= products0[i]['shop']['city']
   nama_toko = products0[i]['shop']['name']

   product = {
      'nama_product' : nama_product,
      'harga_product' : harga_product,
      'diskon_product' : diskon_product,
      'harga_asli' : harga_asli,
      'rating_product' : rating_product,
      'kategori' : kategori,
      'lokasi' : lokasi,
      'nama_toko':nama_toko
   }
   daftar_product0.append(product)

data_frame0 = pd.DataFrame(daftar_product0)
data_frame0

,nama_product,harga_product,diskon_product,harga_asli,rating_product,kategori,lokasi,nama_toko
0,TaffHOME Pencukur Bulu Pakaian Electric Shaver...,22900,0,Rp32.700,4.8,Rumah Tangga,Jakarta Barat,Taffware Official Store
1,Cover Pelindung Baju Jas Cover Pakaian Anti De...,7999,0,Rp12.000,4.9,Rumah Tangga,Kab. Tangerang,Homecart Official Shop
2,Soklin Pemutih Pakaian Botol 1000 ml,18100,0,Rp20.900,4.9,Kesehatan,Bekasi,Wings Official Store
3,PAKET KANTONG PLASTIK VACUM/VAKUM/VACUUM BAG B...,159999,0,,4.9,Rumah Tangga,Jakarta Barat,insideflow
4,MINISO Hanger Klip Simpel 20 pcs Untuk Pengeri...,14900,0,,5.0,Ibu & Bayi,Jakarta Utara,Miniso Indonesia
5,SHINKU - Plastik Vakum Jumbo Kompresi Pakaian ...,74189,0,Rp210.000,4.9,Rumah Tangga,Tangerang Selatan,tataruma.co
6,Vacuum Bag Plastik/ Vacum Bag Travel/ Vakum Pe...,9800,0,Rp15.000,4.9,Rumah Tangga,Jakarta Barat,Toko Murah 2888
7,Baju Kucing Anjing Model Dinosaurus Kostum Cat...,34900,0,Rp39.900,4.9,Perawatan Hewan,Jakarta Barat,Pawsitive Vibes
8,FUYO - Plastik Vakum Kompresi Pakaian Selimut ...,74189,0,Rp210.000,4.9,Rumah Tangga,Tangerang Selatan,tataruma.co
9,Long john Pria / Pakaian dalam musim dingin pr...,199890,0,Rp220.019,4.9,Fashion Pria,Jakarta Barat,Live to Fit Indonesia
10,OHSOME ALBA SOL Lints Roller Pembersih Penghil...,21900,0,Rp32.850,5.0,Rumah Tangga,Kab. Bekasi,OHSOME Indonesia
11,Freeknight Travel Bag Besar Tas Olahraga Gym T...,129000,0,Rp399.000,4.8,Rumah Tangga,Tangerang,Freeknight
12,Goto Sandy Vacuum Bag Travel Vacum Plastik Baj...,51900,0,Rp159.600,4.9,Rumah Tangga,Tangerang,Goto Living
13,MASTERHOME SIKAT SERBAGUNA | SIKAT CUCI BAJU |...,12900,0,Rp25.000,4.9,Rumah Tangga,Jakarta Barat,Master Home Official
14,Rapika Pelicin dan Pewangi Pakaian Sakura Stra...,36600,0,Rp50.400,5.0,Kesehatan,Bekasi,Wings Official Store
15,NAPTOL PEWARNA PAKAIAN JEANS DAN KATUN KEMASAN...,5000,0,,4.8,Office & Stationery,Kab. Sukoharjo,Awan modif sticker
16,SOKA - Kain Ihrom Pria Dewasa Bahan Premium - ...,152100,0,Rp169.000,5.0,Fashion Muslim,Bandung,SOKA INDONESIA
17,Alas gosokan setrika setrikaan gosok Baju Paka...,75500,0,Rp160.000,5.0,Rumah Tangga,Jakarta Timur,Telixmart Official Store
18,Goto Vakugo Vacuum Bag Plastik Vakum Pakaian V...,10900,0,Rp33.000,4.9,Rumah Tangga,Tangerang,Goto Living
19,Vusign Travel Vacuum Bag Kantong Plastik Vacum...,7500,0,,5.0,Rumah Tangga,Kab. Tangerang,Deli Stationery
20,Angola Keranjang Baju Kotor Lipat C14 Laundry ...,99000,0,Rp200.000,4.9,Rumah Tangga,Kab. Tangerang,Angola Indonesia
21,DoraHomi Tas Laundry Bag Kantong Pakaian Jarin...,9500,0,,4.9,Rumah Tangga,Jakarta Timur,DoraHomi
22,Soklin Pewangi Pakaian Cotton Fantasy 1700 ml,32000,0,Rp36.800,5.0,Kesehatan,,Wings Official Store
23,GGT Plastik Vacum Baju Travel Vakum Vacuum Bag...,5639,0,Rp10.000,4.9,Rumah Tangga,Kab. Tangerang,Gudang Grosir Terlengkap
24,DoraHomi Alas gosokan setrikaan Baju Pakaian t...,128500,0,Rp260.000,5.0,Rumah Tangga,Jakarta Timur,DoraHomi
25,PLATO Kantong Baju Tas Travel Bag Organizer Pe...,31000,0,,4.9,Rumah Tangga,Jakarta Utara,TB.Mutiara Jaya
26,DOS Sticky Roll Pembersih Bulu Debu Pakaian Bu...,7467,0,Rp9.872,4.9,Rumah Tangga,Kab. Tangerang,DASYAT ONLINE SHOP
27,Soklin Pelembut Pakaian Love in Paris 820 ml x...,46700,0,Rp50.900,5.0,Kesehatan,Surabaya,Wings Official Store
28,"Pakaian Olahraga Wanita (Fitness,Zumba,Yoga) c...",89999,0,,4.9,Olahraga,Bandung,Fitwear Official
29,U-Living Bundle Vacuum Bag 12pcs Hemat Travel ...,48990,0,Rp120.000,4.9,Rumah Tangga,Bekasi,U-Living Indonesia
30,Vusign Kotak Tempat Pakaian Lipat / Clothes Or...,27000,0,Rp67.500,4.9,Rumah Tangga,Kab. Tangerang,Vusign Home
31,Goto Sandy Vacuum Bag Travel Vacum Plastik Baj...,51900,0,Rp159.600,4.9,Rumah Tangga,Tangerang,GOTO Indonesia
32,Jemuran Handuk Aries Kokoh / Jemuran Pakaian,47500,0,,4.7,Rumah Tangga,Jakarta Barat,Cellis Houseware
33,Vusign Travel Vacuum Bag Pakaian 45 60 CM Wate...,7500,0,Rp16.250,5.0,Rumah Tangga,Kab. Tangerang,Vusign Home
34,Bola Cuci Baju Silicone Laundry Ball Pembersih...,1550,0,Rp1.750,4.8,Rumah Tangga,Tangerang Selatan,jaminmurah899
35,Hicoop Celana pendek polos pakaian dalam HX-01,24900,0,,4.9,Fashion Pria,Jakarta Barat,Hicoop
36,Boxer Isi 6 Celana Dalam Pria Zhfux Emga Pakai...,59999,0,Rp290.000,4.6,Fashion Pria,Surabaya,ZHFU INDONESIA
37,Megam Keranjang Laundry Tempat Pakaian Kotor S...,79900,0,Rp279.000,4.7,Rumah Tangga,Tangerang,Megam Official Shop
38,Box tempat kaos kaki | Tempat pakaian dalam | ...,19500,0,Rp78.000,4.7,Rumah Tangga,Kab. Tangerang,Paus Biru
39,Pandaoma Lint Remover Portable Pembersih Bulu ...,10000,0,Rp50.000,4.9,Rumah Tangga,Surabaya,Pandaoma Official Store
40,Vusign Cover Baju Gantung Resleting Pelindung ...,7500,0,Rp18.750,4.9,Rumah Tangga,Kab. Tangerang,Vusign Home
41,Loxus Instant Rapi - Merapikan Pakaian Kusut S...,25000,0,,4.9,Kesehatan,Bekasi,Loxus Cleaner Official
42,Dekoruma Lemari Pakaian 3 Pintu / Wardrobe - ...,1547000,0,Rp3.182.000,4.8,Rumah Tangga,Kab. Bekasi,Dekoruma Official Store
43,Opelon Pakaian Renang Wanita - Diving Suit Gre...,194750,0,Rp389.500,4.9,Olahraga,Cimahi,Opelon_id
44,"DYLON PEWARNA TEKSTIL / PEWARNA PAKAIAN ""BUNGK...",18000,0,,4.8,Office & Stationery,Jakarta Utara,jahitmart
45,DoraHomi Alas Pelapis Setrika Baju Pakaian Tah...,9000,0,Rp10.000,5.0,Rumah Tangga,Jakarta Timur,DoraHomi
46,Wantex Wantek Pewarna Pakaian Pewarna Textile,2830,0,,4.9,Office & Stationery,Jakarta Pusat,ZHUMAR JAYA INTERLINING
47,Jemuran Baju Pakaian Stainless Steel Panama | ...,559900,0,Rp599.000,4.9,Rumah Tangga,Tangerang,SJ Aluminium
48,wantex pewarna pakaian padi gunting,4500,0,Rp5.000,4.9,Office & Stationery,Bandung,simpati tailor
49,Goto Manual Pump Vacuum Bag Alat Vacum Baju Va...,9900,0,Rp29.600,5.0,Rumah Tangga,Tangerang,Goto Living
50,NEW POMPA VACUUM ELEKTRIK PLASTIK VACUM BAJU A...,25900,0,Rp39.500,4.9,Rumah Tangga,Jakarta Barat,BStore id
51,Vacum Plastik Bag Pakaian Selimut Bantal,9990,0,,4.9,Rumah Tangga,Bandung,Brandystore
52,Set Pakaian Manset Olahraga Pria Baselayer Pro...,34999,0,Rp80.000,4.7,Olahraga,Bandung,Prodigo Official
53,Vacuum Bag Plastik Pakaian Tanpa Pompa Vakum B...,9000,0,Rp28.000,4.9,Rumah Tangga,Tangerang,Nano Care Indonesia
54,SKYE DYE - Pewarna Pakaian - Celup Baju dan Ka...,14499,0,Rp16.100,4.9,Office & Stationery,Kab. Bandung,Benang Jahit Masterpiece
55,Tas Kantung Jaring Laundry Washing Bag Kantong...,2388,0,,4.9,Rumah Tangga,Depok,lbagstore
56,Sea Choice Travel Bag 6 Pcs Tas Kemasan Bagas...,167300,0,Rp239.000,5.0,Rumah Tangga,Kab. Tangerang,Sea Choice Official Store
57,Bh Bra motif Garis Lurus Push Up Style Senam Z...,16888,0,,4.8,Fashion Wanita,Kab. Tangerang,DREAMER FASHION STORE
58,Kostum Imlek - Cosplay Chinese New Year Anabul...,59900,0,Rp125.000,4.5,Perawatan Hewan,Jakarta Barat,Pawsitive Vibes
59,Cubic Lemari Pakaian Minimalis / Wardrobe Baju...,523000,0,Rp1.049.000,4.9,Rumah Tangga,Kab. Gresik,Cubic Home & Living

In [99]:
#SUDAH JADI UNTUK PAGE 2, 3 DST

import requests
import json
import pandas as pd

#referer = 'https://www.tokopedia.com/search?navsource=&page=3&q=halal&search_id=2025021200494626F385AC98EABB30EMBV&srp_component_id=02.01.00.00'

url_target = 'https://gql.tokopedia.com/graphql/SearchProductV5Query'
cari = 'pakaian'

def get_params():
    params=[]
    for i in range(2,100):
        param = "device=desktop&l_name=sre&navsource=&ob=23&page={}&q={}&related=true&rows=60&safe_search=false&scheme=https&shipping=&show_adult=false&source=search&srp_component_id=02.01.00.00&srp_page_id=&srp_page_title=&st=product&start={}&topads_bucket=true&unique_id=c5ed8ccdfa4b87c5d1c9097e7363f4c3&user_id=0&variants=".format(i,cari,(i-1)*60)
        param_strip = param.strip()
        params.append(param_strip)
    return params

def get_referer():
    referers=[]
    for i in range(2,100):
        referer = "https://www.tokopedia.com/search?navsource=&page={}&q={}&search_id=2025021200494626F385AC98EABB30EMBV&srp_component_id=02.01.00.00".format(i,cari)
        referer_strip = referer.strip()
        referers.append(referer_strip)
    return referers

def scrape_data(param,referer):
    header = {'authority': 'gql.tokopedia.com',
        'sec-ch-ua-platform': "Windows",
        'sec-ch-ua': '"Not A(Brand";v="8", "Chromium";v="132", "Google Chrome";v="132"',
        'x-price-center': 'true',
        'iris_session_id': 'd3d3LnRva29wZWRpYS5jb20=.871ebaae251654628a14f3b7a16e6745.1739172229979',
        'bd-device-id': '7459658899563431431',
        'sec-ch-ua-mobile': '?0',
        'accept': '*/*',
        'content-type': 'application/json',
        'x-version': 'd05803b',
        'Referer': '{referer}',
        'x-source': 'tokopedia-lite',
        'x-dark-mode': 'false',
        'tkpd-userid': '0',
        'x-device': 'desktop-0.0',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36',
        'x-tkpd-lite-service': 'zeus'}
    query = f'[{{"operationName":"SearchProductV5Query","variables":{{"params":"{param}"}},"query":"query SearchProductV5Query($params: String\u0021) {{\\n  searchProductV5(params: $params) {{\\n    header {{\\n      totalData\\n      responseCode\\n      keywordProcess\\n      keywordIntention\\n      componentID\\n      isQuerySafe\\n      additionalParams\\n      backendFilters\\n      __typename\\n    }}\\n    data {{\\n      totalDataText\\n      banner {{\\n        position\\n        text\\n        applink\\n        url\\n        imageURL\\n        componentID\\n        trackingOption\\n        __typename\\n      }}\\n      redirection {{\\n        url\\n        __typename\\n      }}\\n      related {{\\n        relatedKeyword\\n        position\\n        trackingOption\\n        otherRelated {{\\n          keyword\\n          url\\n          applink\\n          componentID\\n          products {{\\n            oldID: id\\n            id: id_str_auto_\\n            name\\n            url\\n            applink\\n            mediaURL {{\\n              image\\n              __typename\\n            }}\\n            shop {{\\n              oldID: id\\n              id: id_str_auto_\\n              name\\n              city\\n              tier\\n              __typename\\n            }}\\n            badge {{\\n              oldID: id\\n              id: id_str_auto_\\n              title\\n              url\\n              __typename\\n            }}\\n            price {{\\n              text\\n              number\\n              __typename\\n            }}\\n            freeShipping {{\\n              url\\n              __typename\\n            }}\\n            labelGroups {{\\n              position\\n              title\\n              type\\n              url\\n              styles {{\\n                key\\n                value\\n                __typename\\n              }}\\n              __typename\\n            }}\\n            rating\\n            wishlist\\n            ads {{\\n              id\\n              productClickURL\\n              productViewURL\\n              productWishlistURL\\n              tag\\n              __typename\\n            }}\\n            meta {{\\n              oldWarehouseID: warehouseID\\n              warehouseID: warehouseID_str_auto_\\n              componentID\\n              __typename\\n            }}\\n            __typename\\n          }}\\n          __typename\\n        }}\\n        __typename\\n      }}\\n      suggestion {{\\n        currentKeyword\\n        suggestion\\n        query\\n        text\\n        componentID\\n        trackingOption\\n        __typename\\n      }}\\n      ticker {{\\n        oldID: id\\n        id: id_str_auto_\\n        text\\n        query\\n        applink\\n        componentID\\n        trackingOption\\n        __typename\\n      }}\\n      violation {{\\n        headerText\\n        descriptionText\\n        imageURL\\n        ctaURL\\n        ctaApplink\\n        buttonText\\n        buttonType\\n        __typename\\n      }}\\n      products {{\\n        oldID: id\\n        id: id_str_auto_\\n        name\\n        url\\n        applink\\n        mediaURL {{\\n          image\\n          image300\\n          videoCustom\\n          __typename\\n        }}\\n        shop {{\\n          oldID: id\\n          id: id_str_auto_\\n          name\\n          url\\n          city\\n          tier\\n          __typename\\n        }}\\n        badge {{\\n          oldID: id\\n          id: id_str_auto_\\n          title\\n          url\\n          __typename\\n        }}\\n        price {{\\n          text\\n          number\\n          range\\n          original\\n          discountPercentage\\n          __typename\\n        }}\\n        freeShipping {{\\n          url\\n          __typename\\n        }}\\n        labelGroups {{\\n          position\\n          title\\n          type\\n          url\\n          styles {{\\n            key\\n            value\\n            __typename\\n          }}\\n          __typename\\n        }}\\n        labelGroupsVariant {{\\n          title\\n          type\\n          typeVariant\\n          hexColor\\n          __typename\\n        }}\\n        category {{\\n          oldID: id\\n          id: id_str_auto_\\n          name\\n          breadcrumb\\n          gaKey\\n          __typename\\n        }}\\n        rating\\n        wishlist\\n        ads {{\\n          id\\n          productClickURL\\n          productViewURL\\n          productWishlistURL\\n          tag\\n          __typename\\n        }}\\n        meta {{\\n          oldParentID: parentID\\n          parentID: parentID_str_auto_\\n          oldWarehouseID: warehouseID\\n          warehouseID: warehouseID_str_auto_\\n          isImageBlurred\\n          isPortrait\\n          __typename\\n        }}\\n        __typename\\n      }}\\n      __typename\\n    }}\\n    __typename\\n  }}\\n}}\\n"}}]'
    
    req = requests.post(url_target, headers=header, data=query)
    products = req.json()[0]['data']['searchProductV5']['data']['products']

    #scrape_data=[]
    daftar_product = []
    for j in range(0, len(products)):
        nama_product = products[j]['name']
        harga_product = products[j]['price']['number']
        diskon_product  = products[j]['price']['discountPercentage']
        harga_asli = products[j]['price']['original']
        rating_product = products[j]['rating']
        kategori = products[j]['category']['name']
        lokasi= products[j]['shop']['city']
        nama_toko = products[j]['shop']['name']
        product = {
            'nama_product' : nama_product,
            'harga_product' : harga_product,
            'diskon_product' : diskon_product,
            'harga_asli' : harga_asli,
            'rating_product' : rating_product,
            'kategori' : kategori,
            'lokasi' : lokasi,
            'nama_toko':nama_toko}
        daftar_product.append(product)
    return daftar_product

if __name__ == '__main__' :
    params = get_params()
    referers = get_referer()
    all_data=[]
    for i in range(0,len(params)):
        param = params[i]
        referer=referers[i]
        #print(param)
        #print(referer)
        dataini = scrape_data(param,referer)
        #print(len(params))
        all_data.extend(dataini)

    #print(all_data)
    data_frame = pd.DataFrame(all_data, columns = ['nama_product', 'harga_product', 'diskon_product', 'harga_asli','rating_product','kategori', 'lokasi', 'nama_toko'])

data_frame

,nama_product,harga_product,diskon_product,harga_asli,rating_product,kategori,lokasi,nama_toko
0,UNIKLEN Pembersih Pakaian / UNIKLEEN Penghilan...,18000,0,Rp21.500,4.8,Rumah Tangga,Tangerang Selatan,JNH OFFICIAL SHOP
1,(6 Pcs) Celana Dalam Boxer Pria High Quality P...,53410,0,Rp54.500,4.7,Fashion Pria,Kab. Bandung,MT MajuTerus
2,Kantong Plastik Vakum Transparan Pakaian Selim...,11000,0,Rp19.000,5.0,Rumah Tangga,Bandung,Exa Living
3,U-Living Plastik Vacuum Pakaian Travel Transpa...,5990,0,,5.0,Rumah Tangga,Bekasi,U-Living Indonesia
4,Alat Pembersih Serat Kain Pakaian/Bulu Hewan D...,4900,0,Rp15.000,4.9,Rumah Tangga,Kab. Tangerang,FOCAT Official Store
...,...,...,...,...,...,...,...,...
5875,10 PCS Hanger baju gantungan baju pakaian hang...,15000,0,Rp18.000,5.0,Rumah Tangga,Kab. Tangerang,SHOP AYU
5876,MEGAM Storage Box Pakaian Kotak Penyimpanan Ba...,35900,0,Rp79.000,5.0,Rumah Tangga,Tangerang,Megam Official Shop
5877,ECOCO Laundry Bag - Tas laundry tas cuci Tas l...,20000,0,,5.0,Rumah Tangga,Jakarta Barat,Ecoco Indonesia
5878,Downy Plus Anti Apek Pewangi Pakaian 1.35L Dow...,47500,0,,5.0,Kesehatan,Kab. Ponorogo,Rays_Teknik
5879,JTR CARGO-Tabitha Cortez LPS GT Lemari Pakaian...,452000,0,,5.0,Rumah Tangga,Jakarta Timur,Oscar Living Official

In [100]:
import pandas as pd

df_union = pd.concat([data_frame0, data_frame], ignore_index=True)  # ignore_index untuk reset index
print(df_union)

                                           nama_product  harga_product  \
0     TaffHOME Pencukur Bulu Pakaian Electric Shaver...          22900
1     Cover Pelindung Baju Jas Cover Pakaian Anti De...           7999
2                  Soklin Pemutih Pakaian Botol 1000 ml          18100
3     PAKET KANTONG PLASTIK VACUM/VAKUM/VACUUM BAG B...         159999
4     MINISO Hanger Klip Simpel 20 pcs Untuk Pengeri...          14900
...                                                 ...            ...
5935  10 PCS Hanger baju gantungan baju pakaian hang...          15000
5936  MEGAM Storage Box Pakaian Kotak Penyimpanan Ba...          35900
5937  ECOCO Laundry Bag - Tas laundry tas cuci Tas l...          20000
5938  Downy Plus Anti Apek Pewangi Pakaian 1.35L Dow...          47500
5939  JTR CARGO-Tabitha Cortez LPS GT Lemari Pakaian...         452000

      diskon_product harga_asli rating_product      kategori          lokasi  \
0                  0   Rp32.700            4.8  Rumah Tangga   Jakarta Barat
1                  0   Rp12.000            4.9  Rumah Tangga  Kab. Tangerang
2                  0   Rp20.900            4.9     Kesehatan          Bekasi
3                  0                       4.9  Rumah Tangga   Jakarta Barat
4                  0                       5.0    Ibu & Bayi   Jakarta Utara
...              ...        ...            ...           ...             ...
5935               0   Rp18.000            5.0  Rumah Tangga  Kab. Tangerang
5936               0   Rp79.000            5.0  Rumah Tangga       Tangerang
5937               0                       5.0  Rumah Tangga   Jakarta Barat
5938               0                       5.0     Kesehatan   Kab. Ponorogo
5939               0                       5.0  Rumah Tangga   Jakarta Timur

                    nama_toko
0     Taffware Official Store
1      Homecart Official Shop
2        Wings Official Store
3                  insideflow
4            Miniso Indonesia
...                       ...
5935                 SHOP AYU
5936      Megam Official Shop
5937          Ecoco Indonesia
5938              Rays_Teknik
5939    Oscar Living Official

[5940 rows x 8 columns]

In [101]:
df_union.to_excel('list product pakaian di tokped.xlsx')

In [107]:
len(df_union)
#len(df_union.drop_duplicates())

5940